### ISSUE TITLE
Recreate DownloadButton from V8 viritin

### ISSUE THREAD

**Issue by knoobie** [viritin/flow-viritin#35]
Currently viritin only has a DynamicFileDownloader based on the Anchor component. In the past the DownloadButton extended the Button component resulting in the same visual appearance as other actions and setDisableOnClick which is tremendous important to reduce the duplicate generation of downloads, reducing the stress on server / loads and allowing the user to get instant visible feedback that a task was triggered. 

This feels like an important missing feature in my opinion.

**Comment by mstahv** [comment]
Added some API to make the component appear as Button and a generic method to make the download disabled immediately after it has been clicked. Check out the usage from demo code and let me know if you want something else!

**Comment by knoobie** [comment]
Thanks Matti! Gonna try it next week and give you feedback :)
