### ISSUE TITLE
PagingDataProvider (and maybe also other interfaces) is not marked as Serializable

### ISSUE THREAD

**Issue by jorgheymans** [viritin/flow-viritin#65]
Like #61 and #52 , `PagingGrid.PagingDataProvider` is not marked as Serializable. We can work around it but it would be nice to have this serializable by default for easy lambda style creation.

Perhaps there are more interfaces in Viritin that will be likely used as lambdas and end up in the session, and they could all be marked as Serializable in one go ?

**Comment by mstahv** [comment]
Should set some similar build time check that all interfaces are serializable as we have in the framework project.

**Comment by jorgheymans** [comment]
Thanks!
