### ISSUE TITLE
DynamicFileDownloader starts download when disabled

### ISSUE THREAD

**Issue by mattesnom** [viritin/flow-viritin#67]
Steps to reproduce:

1. Add DynamicFileDownloader in disabled state to UI (clicking doesn't start download)
2. enable DynamicFileDownloader 
3. disable DynamicFileDownloader
4. click on DynamicFileDownloader starts download

**Comment by mstahv** [comment]
Fixed, release in progress.

**Comment by mattesnom** [comment]
Great, thank you
