### ISSUE TITLE
`VHorizontalLayout` defaults broke many layouts

### ISSUE THREAD

**Issue by oliveryasuna** [viritin/flow-viritin#71]
See https://github.com/viritin/flow-viritin/commit/edd7c5933c64561362c60a510fbf2dce2a0ceea8.

I think that this should be either reverted, or introduced in a new major version release.

**Comment by mstahv** [comment]
Agreed, I noticed this myself in one demo as well. Reverted now for 2.8.26. I think I even promised to revert it earlier, but it was too hectic comeback to work, sorry for the delay.

As the baseline is the correct value, for most case 🤓, I created a new component, HorizontalFloatLayout. Not sure if the name is great. In addition to baseline alignment it also wraps if there is too many components to fit into horizontal space.
