### ISSUE TITLE
Open file in new tab with DynamicFileDownloader

### ISSUE THREAD

**Issue by urkl** [viritin/flow-viritin#72]
What is the easiest way to open file in new tab, for example pdf? 

I need dynamicaly named pdf's opened in new tab.

**Comment by mstahv** [comment]
DynamicFileDownloader is meant to download files :-) But I see your point, you'd like the similar simple API to generate file contents on the file to display PDF:s and similar other files that browser can display. Removing the _download_ attribute and adding _target_  with __new_ might do it.

I wonder if it should be a separate component or configuration option 🤔

**Comment by urkl** [comment]
Tanks for response. I would say that it's a configuration setting since it's still about downloading a file, it just doesn't open inline but rather in a new browser tab.

**Comment by urkl** [comment]
Tanks for response. I would say that it's a configuration setting since it's still about downloading a file, it just doesn't open inline but rather in a new browser tab.

**Comment by mstahv** [comment]
It depends from which side you are looking at it. From the users/browsers point of view, it is not a download, but from the server it is same kind of sending of bytes to the client 🤷‍♂️

**Comment by mstahv** [comment]
2.9.1 (out soon) will contain *inNewWindow()*, check out if that suits for you.

**Comment by urkl** [comment]
Thanks!

**Comment by urkl** [comment]
Works like charm!  Matti thank you.
